language: go

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
install: go get -u golang.org/x/oauth2
script:
- set -e
- GOOS=linux   GOARCH=amd64 go install ./...
- GOOS=darwin  GOARCH=amd64 go install ./...
- GOOS=windows GOARCH=amd64 go install ./...
- set +e

jobs:
  include:
    - stage: run tests
      go: 1.9.x
      install: go get -u golang.org/x/oauth2
      script: go test ./dropbox/...
